config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects

  root 'static_pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.paginate(page: params[:page])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:notice] = "#{@user.name.capitalize} has been created!"
    else
      flash.now[:warning] = "No user has been created!"
    end
    render 'new'
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash.now[:notice] = "#{user.name} was removed."
  end

  def new
    @user = User.new
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
      <div class="container-fluid">
        <p class="pull-left">
          Interview Project &copy; Chris Barthol 2015
        </p>
        <span class="pull-right">
            About Contact
        </span>
      </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Superior Construction</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Projects', projects_path %></li>
            <li><a href="#">Materials</a></li>
            <!-- <li><a href="#">Schedule</a></li> -->
            <li role="separator" class="divider"></li>
            <li><a href="#">Consultation</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Employees <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All', users_path %></li>
            <li><%= link_to 'New', new_user_path %></li>
          </ul>
        </li>        
        <!-- <li><a href="#">User</a></li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyInterviewApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_project.html.erb
<li>
  <div><%= project.name %></div>
  <div><%= project.description %></div>
</li>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<%= will_paginate %>

<ul class="employees">
  <%= render @projects %>
</ul>

<%= will_paginate %>

app/views/static_pages/home.html.erb
<div class="center hero-unit text-center">
  <h1>Superior Construction Internal Application (SCIA)</h1>

  <h2>
    Requirements List
  </h2>
  <ol>
    <li>
      Jill just got married and needs to change her name.  The current app does not allow this action to happen.
      Allow updates to the employees.
    </li>
    <li>
      We've noticed duplicate users on the Users index page. Write a rake task to clean these entries up and put in
      a fix to not allow this to happen.
    </li>
    <li>
      We currently have a excel list of all employees working on each project.  We would like to see this data in
      the app.  Each project should list the employees working on the project and each employee should show which projects
      they are working on.
    </li>
    <li>
      Each project has a list of materials.  Define the model and relationships.  Each project should show the materials needed
      to complete the project.  We would also like to have an inventory page to keep track of all our materials.
    </li>
  </ol>
</div>

app/views/users/_create_fields.html.erb
<%#= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  |
  <%= link_to user.email, user %>
</li>

app/views/users/index.html.erb
<h1>All Employees</h1>
<%= will_paginate %>

<ul class="employees">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Create new Users</h1>
</div>
<div>
  <%= form_for(@user) do |f| %>
    <%= render 'create_fields', f: f %>
    <%= f.submit "Create a new User", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="center hero-unit">
  <%= @user.name %>
</div>